### ISSUE TITLE
example/main.go fails with `err: socket: operation not supported by device`

### ISSUE THREAD

**Issue by cfergeau** [Code-Hex/darwin-vsock#1]
Just to make sure my understanding is correct, is it expected that build and running `example/main.go` on macOS 11 returns `err: socket: operation not supported by device` when run on the host?

According to `man vsock`, this is normal, but I wanted to make sure this matches your experience.

> Currently, only stream connections from a guest are supported using this

**Comment by Code-Hex** [comment]
@cfergeau I just noticed your comment!

I'm using macOS 11.6（20G165）now. The answer is Yes.

> s it expected that build and running example/main.go on macOS 11 returns err: socket: operation not supported by device when run on the host?

As a result, development in this repository has not been active.
